apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

nameSuffix: -dev

replicas:
  - name: platform-status
    count: 1

patches:
  - target:
      kind: Ingress
      name: platform-status
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: platform-dev.local