apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet

metadata:
  name: platform-status
  namespace: argocd

spec:
  generators:
    - list:
        elements:
          - environment: dev
            namespace: platform-status

  template:
    metadata:
      name: "platform-status-{{environment}}"

    spec:
      project: default

      source:
        repoURL: https://github.com/krypt0-cappy/platform-status-lab.git
        targetRevision: main
        path: "apps/platform-status/overlays/{{environment}}"

      destination:
        server: https://kubernetes.default.svc
        namespace: "{{namespace}}"

      syncPolicy:
        syncOptions:
          - CreateNamespace=true